# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 07:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('type', models.CharField(choices=[('registration', 'Registration'), ('notification', 'Notification'), ('subscription', 'Subscription')], max_length=32)),
                ('application', models.CharField(max_length=32)),
                ('notification', models.CharField(blank=True, max_length=32)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
