# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webgntp', '0002_prowlkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('sent', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('error', 'error')], max_length=32)),
                ('notification', models.CharField(max_length=32)),
            ],
        ),
    ]
