# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgntp', '0005_auto_20160327_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
