# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgntp', '0006_notification_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
